### ISSUE TITLE
EH-60   Netlify build failed .. after latest merge to main

### ISSUE THREAD

**Issue by ifoi** [ifoi/edishub#28]
@RoodzFernando   please take a look .. 

  here is a copy of part of the logs related to the error .. 

"4:00:00 AM: ​
4:00:00 AM: Packaging Edge Functions from .netlify/edge-functions directory:
4:00:00 AM:  - ipx
4:00:02 AM: error: Uncaught (in promise) Error: Module not found "https://deno.land/std@0.136.0/async/deadline.ts".
4:00:02 AM:       const ret = new Error(getStringFromWasm0(arg0, arg1));
4:00:02 AM:                   ^
4:00:02 AM:     at __wbg_new_651776e932b7e9c7 (file:///opt/buildhome/node-deps/node_modules/@netlify/edge-bundler/deno/vendor/deno.land/x/eszip@v0.28.0/eszip_wasm.generated.js:313:19)
4:00:02 AM:     at <anonymous> (wasm://wasm/00a90a36:1:78732)
4:00:02 AM:     at <anonymous> (wasm://wasm/00a90a36:1:1463894)
4:00:02 AM:     at <anonymous> (wasm://wasm/00a90a36:1:1957066)
4:00:02 AM:     at __wbg_adapter_18 (file:///opt/buildhome/node-deps/node_modules/@netlify/edge-bundler/deno/vendor/deno.land/x/eszip@v0.28.0/eszip_wasm.generated.js:144:6)
4:00:02 AM:     at real (file:///opt/buildhome/node-deps/node_modules/@netlify/edge-bundler/deno/vendor/deno.land/x/eszip@v0.28.0/eszip_wasm.generated.js:128:14)
4:00:02 AM: ​
4:00:02 AM: ────────────────────────────────────────────────────────────────
4:00:02 AM:   Bundling of edge function failed                              
4:00:02 AM: ────────────────────────────────────────────────────────────────
4:00:02 AM: ​
4:00:02 AM:   Error message
4:00:02 AM:   Command failed with exit code 1: deno run --allow-all --no-config --quiet --import-map=/opt/buildhome/node-deps/node_modules/@netlify/edge-bundler/deno/vendor/import_map.json /opt/buildhome/node-deps/node_modules/@netlify/edge-bundler/deno/bundle.ts {"basePath":"/opt/build/repo","destPath":"/tmp/edge-636e00bbd47f900009041575/b6cb825e-0185-4ee2-b594-32c8420b6e15.eszip","functions":[{"name":"ipx","path":"/opt/build/repo/.netlify/edge-functions/ipx/index.ts"}],"importMapURL":"data:application/json;base64,eyJpbXBvcnRzIjp7Im5ldGxpZnk6ZWRnZSI6Imh0dHBzOi8vZWRnZS5uZXRsaWZ5LmNvbS92MS9pbmRleC50cyJ9fQ=="} (https://ntl.fyi/exit-code-1)
4:00:02 AM:   error: Uncaught (in promise) Error: Module not found "https://deno.land/std@0.136.0/async/deadline.ts".
4:00:02 AM:         const ret = new Error(getStringFromWasm0(arg0, arg1));
4:00:02 AM:                     ^
4:00:02 AM:       at __wbg_new_651776e932b7e9c7 (file:///opt/buildhome/node-deps/node_modules/@netlify/edge-bundler/deno/vendor/deno.land/x/eszip@v0.28.0/eszip_wasm.generated.js:313:19)
4:00:02 AM:       at <anonymous> (wasm://wasm/00a90a36:1:78732)
4:00:02 AM:       at <anonymous> (wasm://wasm/00a90a36:1:1463894)
4:00:02 AM:       at <anonymous> (wasm://wasm/00a90a36:1:1957066)
4:00:02 AM:       at __wbg_adapter_18 (file:///opt/buildhome/node-deps/node_modules/@netlify/edge-bundler/deno/vendor/deno.land/x/eszip@v0.28.0/eszip_wasm.generated.js:144:6)
4:00:02 AM:       at real (file:///opt/buildhome/node-deps/node_modules/@netlify/edge-bundler/deno/vendor/deno.land/x/eszip@v0.28.0/eszip_wasm.generated.js:128:14)
4:00:02 AM: ​
4:00:02 AM:   Error location
4:00:02 AM:   While bundling edge function"

**Comment by ifoi** [comment]
the contact form is based on the code from the netlify nextjs toolbox  https://github.com/netlify-templates/nextjs-toolbox/blob/main/components/FeedbackForm.js
